name: Publish to PowerShell Gallery

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate module
      run: |
        Test-ModuleManifest .\JDKManager\JDKManager.psd1
        Import-Module .\JDKManager\JDKManager.psd1 -Force
        Get-Command -Module JDKManager
        
    - name: Get version from manifest
      id: version
      run: |
        $manifest = Test-ModuleManifest .\JDKManager\JDKManager.psd1
        echo "version=$($manifest.Version)" >> $env:GITHUB_OUTPUT
        
    # - name: Publish to PowerShell Gallery
    #   run: |
    #     Publish-Module -Path .\JDKManager -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }} -Repository PSGallery -Force
    #   env:
    #     PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        
    - name: Create Release
      run: |
        $version = "${{ steps.version.outputs.version }}"
        gh release create "v$version" --title "JDKManager v$version" --notes "PowerShell Gallery release v$version" --draft false --prerelease false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 